# Basic action to automatically pull new code on webserver

name: autodeploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH into webserver and git pull
        run: |
          echo $SSH_KEY > ./id_rsa
          ssh -i ./id_rsa autodeploy@webbgamers.tech "cd /home/pi/webbgamers.tech; git pull"
